export const queryKeys = {
  session: ["session"] as const,
  currentUser: ["currentUser"] as const,
  profile: (userId: string) => ["profile", userId] as const,
  loginDepartments: ["loginDepartments"] as const,
  loginUsersByRole: (roleKey: string) => ["loginUsersByRole", roleKey] as const,
  poList: (filters?: Record<string, unknown>) => ["poList", filters] as const,
  po: (poId: string) => ["po", poId] as const,
  poActivity: (poId: string) => ["poActivity", poId] as const,
  item: (itemId: string) => ["item", itemId] as const,
  itemProgress: (itemId: string) => ["itemProgress", itemId] as const,
  itemProblems: (itemId: string) => ["itemProblems", itemId] as const,
  itemAuditLog: (itemId: string) => ["itemAuditLog", itemId] as const,
  tasks: (roleKey: string, filters?: Record<string, unknown>) => ["tasks", roleKey, filters] as const,
  taskArchive: (roleKey: string, month?: string) => ["taskArchive", roleKey, month] as const,
  board: (filters?: Record<string, unknown>) => ["board", filters] as const,
  boardItem: (itemId: string) => ["boardItem", itemId] as const,
  notifications: (userId: string) => ["notifications", userId] as const,
  notificationCount: (userId: string) => ["notificationCount", userId] as const,
  finance: (tab?: string, filters?: Record<string, unknown>) => ["finance", tab, filters] as const,
  financeCounts: (filters?: Record<string, unknown>) => ["financeCounts", filters] as const,
  dashboard: (period?: string) => ["dashboard", period] as const,
  dashboardKpis: (period?: string) => ["dashboardKpis", period] as const,
  dashboardCharts: (period?: string) => ["dashboardCharts", period] as const,
  problems: (filters?: Record<string, unknown>) => ["problems", filters] as const,
  problem: (problemId: string) => ["problem", problemId] as const,
  settingsWorkspace: ["settingsWorkspace"] as const,
  settingsUsers: ["settingsUsers"] as const,
  settingsClients: ["settingsClients"] as const,
  settingsFlags: ["settingsFlags"] as const,
  departments: ["departments"] as const,
  superadminWorkspaceConfig: ["superadminWorkspaceConfig"] as const,
  superadminDepartments: ["superadminDepartments"] as const,
  superadminBilling: ["superadminBilling"] as const,
  auditLog: (itemId: string) => ["auditLog", itemId] as const,
};
